version: "3.8"
services:
  mongodb:
    image : mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - postgres-network

  postgres:
    image: postgres:11.1
    container_name: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - METABASE_PASSWORD=docker
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: always
  
  metabase:
    volumes:
      - ./db:/db-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=docker
      - MB_DB_PORT=5432
      - MB_DB_USER=docker
      - MB_DB_PASS=docker
      - MB_DB_HOST=postgres
    ports:
      - 3000:3000
    image: metabase/metabase
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres-network

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_SERVER: mongodb

  # python_app:
  #   container_name: python_app
  #   restart: always
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile

networks:
    postgres-network:
     driver: bridge