version: "3.8"
services:
  mongodb:
    image : mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    restart: always

  postgres:
    image: postgres:11.1
    container_name: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: always
  
  metabase:
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=DATABASE
      - MB_DB_PORT=5432
      - MB_DB_USER=USERNAME
      - MB_DB_PASS=PASWORD
      - MB_DB_HOST=db
    ports:
      - 3000:3000
    image: metabase/metabase
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres-network

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   ports:
  #     - 8081:8081
  #   restart: always
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: password
  #     ME_CONFIG_MONGODB_SERVER: mongodb

  # python_app:
  #   container_name: python_app
  #   restart: always
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile

networks:
    postgres-network:
     driver: bridge