version: "3.8"
services:
  mongodb:
    image : mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lappis
      - MONGO_INITDB_ROOT_PASSWORD=lappis
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - postgres-network

  postgres:
    image: postgres:11.1
    container_name: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lappis
      - POSTGRES_PASSWORD=lappis
      - METABASE_PASSWORD=lappis
    ports:
      - 5432:5432
    networks:
      - postgres-network
    restart: always
  
  metabase:
    volumes:
      - ./db:/db-data
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=lappis
      - MB_DB_PORT=5432
      - MB_DB_USER=lappis
      - MB_DB_PASS=lappis
      - MB_DB_HOST=postgres
    ports:
      - 3000:3000
    image: metabase/metabase
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: lappis
      ME_CONFIG_MONGODB_ADMINPASSWORD: lappis
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - postgres-network

  # python_app:
  #   container_name: python_app
  #   restart: always
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile

networks:
    postgres-network:
     driver: bridge